name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./twitter

    steps:
      - uses: actions/checkout@v4
      - name: 'Create env file'
        run: echo "${{ secrets.TWITTER_CLONE_ENV_PRODUCTION }}" > .env.production
      - name: Build the Docker image
        run: docker build --progress=plain -t phanhung8/twitter:v1 .
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push the Docker image
        run: docker push phanhung8/twitter:v1